name: aeraa
description: "A new Flutter project."
publish_to: 'none'
version: 3.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  window_manager: ^0.5.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.17.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true

msix_config:
  display_name: Aeraa
  publisher_display_name: Sparsh
  identity_name: com.sparsh.aeraa
  logo_path: windows/runner/resources/app_icon.ico



flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/app_icon.png" # Path to your source icon
    icon_size: 48 # Optional: Default is 48
  image_path: "assets/images/app_icon.png"